// Two-tier SVG cache for the playground.
//
// Tier 1 (build-time, immutable): `prerendered.json` is generated by
// `scripts/prerender.ts` for every curated example in `examples.ts`.
// It ships in the SPA bundle, so dropdown switches render directly
// from memory with no API call.
//
// Tier 2 (runtime, mutable): user-edited code that successfully
// renders gets cached to localStorage. So if a course instructor
// preps a half-dozen examples in their browser before lecture, every
// re-render in front of the class is instant — only the first render
// per snippet hits the API.
//
// Both tiers key on `sha256(code)`. Code matches must be exact (we
// don't normalize whitespace) — a stray edit invalidates the entry,
// which is what you want: any change to the source could change the
// rendering.
//
// Invalidation: the prerendered map ships with a `version` (the git
// commit hash at build time). The runtime tier carries the version
// it was created under. On boot we sweep any localStorage entries
// whose version doesn't match the current build, so a fresh deploy
// drops the entire user-side cache atomically and we never serve a
// stale rendering against a newer plugin.

import prerendered from './prerendered.json';

export type SvgPair = {
  code_panel: string;
  timeline_panel: string;
};

type PrerenderManifest = {
  version: string;
  entries: Record<string, SvgPair>;
};

const PR = prerendered as PrerenderManifest;

const RUNTIME_KEY_PREFIX = 'rustviz.svgcache.';
const RUNTIME_VERSION_KEY = 'rustviz.svgcache.version';

/**
 * Drop every runtime cache entry tagged with a different build
 * version than what's currently bundled. Called once on module load
 * — cheap (one-time scan over `localStorage` keys) and keeps the
 * cache from growing without bound across deploys.
 */
function sweepStaleEntries(): void {
  try {
    const recordedVersion = localStorage.getItem(RUNTIME_VERSION_KEY);
    if (recordedVersion === PR.version) return; // already current

    const toRemove: string[] = [];
    for (let i = 0; i < localStorage.length; i++) {
      const k = localStorage.key(i);
      if (k && k.startsWith(RUNTIME_KEY_PREFIX) && k !== RUNTIME_VERSION_KEY) {
        toRemove.push(k);
      }
    }
    for (const k of toRemove) localStorage.removeItem(k);
    localStorage.setItem(RUNTIME_VERSION_KEY, PR.version);
  } catch {
    // localStorage disabled (private browsing, quota issues). The
    // cache silently degrades to "build-time tier only", which is
    // still a big win over no cache.
  }
}

sweepStaleEntries();

/**
 * Browser-native SHA-256 returning lowercase hex. `subtle.digest` is
 * async (and only synchronous on a worker), so the cache lookup path
 * is async too — fits naturally into Generate's existing async flow.
 */
async function sha256Hex(s: string): Promise<string> {
  const buf = new TextEncoder().encode(s);
  const hash = await crypto.subtle.digest('SHA-256', buf);
  return Array.from(new Uint8Array(hash))
    .map(b => b.toString(16).padStart(2, '0'))
    .join('');
}

function runtimeKey(hash: string): string {
  return RUNTIME_KEY_PREFIX + hash;
}

/**
 * Look the snippet up in the cache. Returns `null` on miss; caller
 * is responsible for falling back to the API and (on success)
 * calling `put`.
 *
 * Build-time entries take priority over runtime — if a snippet
 * happens to match a curated example, the prebuilt SVGs are
 * canonical regardless of any older user-side rendering.
 */
export async function get(code: string): Promise<SvgPair | null> {
  const hash = await sha256Hex(code);
  const fromBuild = PR.entries[hash];
  if (fromBuild) return fromBuild;
  try {
    const raw = localStorage.getItem(runtimeKey(hash));
    if (!raw) return null;
    const parsed: unknown = JSON.parse(raw);
    if (
      parsed &&
      typeof (parsed as SvgPair).code_panel === 'string' &&
      typeof (parsed as SvgPair).timeline_panel === 'string'
    ) {
      return parsed as SvgPair;
    }
  } catch {
    // corrupt localStorage entry — treat as miss; next put() overwrites
  }
  return null;
}

/**
 * Memoize a successful API render. Build-time entries are immutable
 * and we don't bother trying to overwrite them — the prebuilt set
 * is exactly the dropdown list, so any successful API render is by
 * definition a user-side snippet.
 *
 * Storage failure is silent: localStorage might be full, disabled,
 * or in a private-browsing mode that quota-throttles it. Either way
 * the SPA already has the rendering from the API response in memory
 * for this session; missing the persistent cache just means a re-run
 * later will re-pay the API cost.
 */
export async function put(code: string, pair: SvgPair): Promise<void> {
  const hash = await sha256Hex(code);
  if (PR.entries[hash]) return;
  try {
    localStorage.setItem(runtimeKey(hash), JSON.stringify(pair));
  } catch {
    // Quota / disabled. See comment above.
  }
}

/**
 * Stats useful for debugging. Not part of the runtime hot path —
 * called from the dev tools or a `?debug` query param if we ever
 * surface that. Kept here so the implementation details don't leak
 * out into App.tsx.
 */
export function stats(): { prebuilt: number; runtime: number; version: string } {
  let runtime = 0;
  try {
    for (let i = 0; i < localStorage.length; i++) {
      const k = localStorage.key(i);
      if (k && k.startsWith(RUNTIME_KEY_PREFIX) && k !== RUNTIME_VERSION_KEY) {
        runtime += 1;
      }
    }
  } catch {
    // ignore
  }
  return {
    prebuilt: Object.keys(PR.entries).length,
    runtime,
    version: PR.version,
  };
}
